### ISSUE TITLE
Stack size

### ISSUE THREAD

**Issue by shiozaki** [qsimulate-open/bagel#2]
Stack size for integral evaluation is hardwired to 80M (?) now. This is especially problematic for relativistic (gradient) calculations where one sometimes needs to increase the size manually.

**Comment by jesusG-V** [comment]
Where should I change this value?
I am trying to run Iodine atom and fails due to stacksize...
By the way, there is any way to print the relativistic orbitals as combination of the basis (maybe a molden file with imaginary numbers)?
Thanks,
Jesús

**Comment by jesusG-V** [comment]
I did not realize, that is a very old issue, sorry for the inconvinience

**Comment by RDReynolds** [comment]
You can edit line 57 of src/util/parallel/resource.h:

    StackMem() : pointer_(0LU), total_(20000000LU) { // TODO 80MByte

Increase that 20,000,000 parameter to the desired value.  You will have to recompile nearly all of BAGEL after editing this file.  

I will respond to your other question via email since it is unrelated to the Stack size issue.

**Comment by shiozaki** [comment]
In principle, the users should not have to modify this value... Ryan do you know when this happens? Jesus: Can you tell us what kind of calculations did you try to do?

One option is to make this an input parameter, but I personally don't like that.

**Comment by jesusG-V** [comment]
Dear all,

Attached to this mail, I send you a file with the problem. I am checking if I can use a variational method to improve the spectrum of halomethanes that we did some time ago (https://doi.org/10.1016/j.cplett.2017.02.037). As a first trial, I just focus in the haolgen atoms to see how it works and I found this problem when running Iodine atom, there are not too many basis functions (52) but it fails due to a stack memory problem. I check and it works with the 3-21G (also in the file) where the number of basis is 31.

[HALO.zip](https://github.com/nubakery/bagel/files/1024617/HALO.zip)

**Comment by shiozaki** [comment]
Jesus, can I see the basis file? On a separate note, perhaps you should uncontract the df basis (uncontracted ANO-RCC would be fine).

**Comment by shiozaki** [comment]
Oh never mind, I found in the zip file. Let me back to you later.

**Comment by jesusG-V** [comment]
It is now working by using 1GB of stack memory:

    StackMem() : pointer_(0LU), total_(250000000LU) { // TODO 1000MByte
