### ISSUE TITLE
Question: Is there a possibility of importing orbital data from CASSCF of other programs?

### ISSUE THREAD

**Issue by Alexandr-Zaykov** [qsimulate-open/bagel#214]
Dear developers,

I wanted to ask, whether there is a way how to import CASSCF calculation data (be it RDM or orbital data) from other programs such as PySCF. PySCF supports some features (such as SHCISCF), which would benefit my molecule greatly, alas it does not have analytical gradients for XMS-CASPT2.
Therefore, I am looking for a way how to pair the programs, if it is even possible.
Thank you!

**Comment by shiozaki** [comment]
You can interface an external FCI engine to CASSCF and CASPT2 code. However, in order to calculate analytic gradients, one has to solve a response equation, which is not possible with SHCISCF (or other external engines).

There is ongoing work to realize DMRG-CASPT2 nuclear gradients by solving the DMRG response equation, but it's not available at this time.

**Comment by shiozaki** [comment]
Let me close this now, as there is no action item...
