### ISSUE TITLE
Ecp basis set

### ISSUE THREAD

**Issue by darkcoordinate** [qsimulate-open/bagel#274]
calculation with custom basis set with ecp parameters is not working.

**Comment by Moritz-Limbacher** [comment]
I had an issue with a basis set from basis set exchange which I converted into the bagel format. 
Stating the error:   ERROR ON MPI PROCESS 1: EXCEPTION RAISED:  A required keyword is missing from the input:  angular
It did not work, until I added "ecp" to the name (def2-tzvp.json => def2-tzvp-ecp.json). Then it worked properly. 

this might be caused by adding the "valence" and "core" to the basis set when an ECP is used.
Without ECP, "valence" is not required. check out the format of existing basis sets, provided by bagel.

**Comment by Piju123** [comment]
Dear BAGEL Support Team,

I want to use the ECP basis for Au atom but all ecp basis sets available in BAGEL are not working. However, for Cu atom it's work perfectly. 
I am also tried using a user defined basis for e.g. laln2dz-au-ecp.json and still this did not work for Au atom.   

I am getting the error like  A required keyword is missing from the input. 

Can you suggests me any way out of this problem ?   Looking forward to your kind reply. 

with regards,
Pijush Karak
PhD
University of Calcutta
